---
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: memory_use_percent
  - type: swap_use_percent
  - type: processor_use
  - type: network_in
    arg:  eth0
  - type: network_out
    arg:  eth0

- platform: template
  sensors:
    james_***REMOVED***_bluetooth_rssi:
      friendly_name: James' ***REMOVED*** Bluetooth RSSI
      value_template: "{{ state_attr('device_tracker.james_***REMOVED***_bluetooth', 'rssi')[0] | float }}"
      entity_id: device_tracker.james_***REMOVED***_bluetooth
