---
alert: !include_dir_merge_named ./partials/alerts/
automation: !include_dir_merge_list ./partials/automations/
binary_sensor:
- platform: template
  sensors: !include_dir_merge_named ./partials/binary_sensors/
config: null
device_tracker:
- platform: bluetooth_tracker
  request_rssi: true
  new_device_defaults:
    track_new_devices: false
duckdns:
  access_token: !secret duck_dns_token
  domain: !secret duck_dns_domain
frontend:
  themes: !include_dir_merge_named ./themes/
hacs:
  sidepanel_icon: mdi:account-group
  theme: true
  token: !secret github_token_hacs
history: null
homeassistant:
  customize: !include ./partials/customize.yaml
  elevation: 43
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  name: Home
  temperature_unit: F
  time_zone: America/Los_Angeles
  unit_system: imperial
http:
  server_port: 443
  ssl_certificate: /config/tls/certificate.pem
  ssl_key: /config/tls/privkey.pem
logbook: null
logger:
  default: info
mobile_app: null
notify: !include_dir_merge_list ./partials/notifiers/
person:
- name: James
  id: james
  user_id: !secret user_id_james
  device_trackers:
  - device_tracker.james_***REMOVED***
sensor: !include ./partials/sensors.yaml
sun: null
system_health: null
telegram_bot:
- platform: broadcast
  api_key: !secret telegram_bot_token
  allowed_chat_ids:
  - !secret telegram_chat_id
updater:
  include_used_components: true
  reporting: true
weather:
- platform: darksky
  api_key: !secret darksky_api_key
  mode: daily
  name: Home
zeroconf: null
zwave:
  network_key: !secret zwave_network_key
  usb_path: /dev/ttyUSB0
