---
config:
history:
logbook:
#map:
mobile_app:
sun:
system_health:
zeroconf:

alert:          !include_dir_merge_named configs/alerts/
automation:     !include_dir_merge_list configs/automations/
binary_sensor:  !include configs/binary_sensors.yaml
device_tracker: !include configs/device_trackers.yaml
duckdns:        !include configs/duckdns.yaml
edgeos:         !include configs/edgeos.yaml
frontend:       !include configs/frontend.yaml
group:          !include configs/groups.yaml
hacs:           !include configs/hacs.yaml
homeassistant:  !include configs/home_assistant.yaml
input_text:     !include configs/input_texts.yaml
logger:         !include configs/logger.yaml
notify:         !include configs/notifiers.yaml
person:         !include configs/people.yaml
script:         !include configs/scripts.yaml
sensor:         !include configs/sensors.yaml
system_log:     !include configs/system_log.yaml
updater:        !include configs/updater.yaml
weather:        !include configs/weather.yaml
zone:           !include configs/zones.yaml
zwave:          !include configs/zwave.yaml
