---
alert: !include_dir_merge_named ./partials/alerts/
automation: !include_dir_merge_list ./partials/automations/
binary_sensor:
- platform: template
  sensors: !include_dir_merge_named ./partials/binary_sensors/
config: null
device_tracker:
- platform: bluetooth_tracker
  device_id: 1
  request_rssi: true
  new_device_defaults:
    track_new_devices: false
- platform: ping
  scan_interval: 15
  count: 10
  hosts:
    wifi_james_mobile_1: !secret ip_addr_james_mobile_1
    wifi_james_mobile_2: !secret ip_addr_james_mobile_2
    wifi_james_mobile_3: !secret ip_addr_james_mobile_3
frontend:
  themes: !include_dir_merge_named ./themes/
hacs:
  sidepanel_icon: mdi:account-group
  theme: true
  token: !secret github_token_hacs
history: null
homeassistant:
  customize: !include ./partials/customizations.yaml
  elevation: 43
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  name: Home
  temperature_unit: F
  time_zone: America/Los_Angeles
  unit_system: imperial
http:
  server_port: 443
  ssl_certificate: /config/tls/certificate.pem
  ssl_key: /config/tls/privkey.pem
logbook: null
logger:
  default: info
# map: null
mobile_app: null
# mqtt:
#   broker: !secret mqtt_broker_address
#   port: !secret mqtt_broker_port
#   username: !secret mqtt_broker_username
#   password: !secret mqtt_broker_password
notify:
- platform: telegram
  name: telegram
  chat_id: !secret telegram_chat_id
# owntracks:
#   max_gps_accuracy: 200
#   secret: !secret owntracks_secret
person:
- name: James
  id: james
  user_id: !secret user_id_james
  device_trackers:
  - device_tracker.bluetooth_james_mobile
  # - device_tracker.owntracks_james_mobile
  - device_tracker.wifi_james_mobile_1
  - device_tracker.wifi_james_mobile_2
  - device_tracker.wifi_james_mobile_3
sensor: !include ./partials/sensors.yaml
sun: null
system_health: null
telegram_bot:
- platform: broadcast
  api_key: !secret telegram_bot_token
  allowed_chat_ids:
  - !secret telegram_chat_id
updater:
  include_used_components: true
  reporting: true
weather:
- platform: darksky
  api_key: !secret darksky_api_key
  mode: daily
  name: Home
zeroconf: null
# zone:
# - name: Home
#   latitude: !secret zone_home_latitude
#   longitude: !secret zone_home_longitude
#   radius: 25
#   icon: mdi:home
# - name: Work
#   latitude: !secret zone_work_latitude
#   longitude: !secret zone_work_longitude
#   radius: 75
#   icon: mdi:floppy
zwave:
  network_key: !secret zwave_network_key
  usb_path: /dev/ttyUSB0
