---
- alias: Garage Door Opened
  description: Garage door has been opened
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door
    from: "off"
    to: "on"
  action:
  - delay: "00:00:30"
  - condition: state
    entity_id: person.james
    state: not_home
  - service: notify.telegram
    data:
      message: Your garage door has been opened
  - service: notify.discord_alerts_home
    data:
      message: >
        Your garage door has been opened
        <@{{ states('input_text.discord_user_id') }}>

- alias: Garage Door Left Opened
  description: Garage door has been left opened
  trigger:
  - platform: state
    entity_id: person.james
    from: home
    to: not_home
  condition:
  - condition: state
    entity_id: binary_sensor.garage_door
    state: "on"
  action:
  - service: notify.telegram
    data:
      message: You left your garage door open
  - service: notify.discord_alerts_home
    data:
      message: >
        You left your garage door open
        <@{{ states('input_text.discord_user_id') }}>

- alias: Garage Door Sensor Body Opened
  description: Garage door sensor body has been opened up
  trigger:
  - platform: state
    entity_id: sensor.garage_door_tamper_alarm
    from: "0"
    to: "3"
  action:
  - service: notify.telegram
    data:
      message: The garage door sensor's body has been opened
  - service: notify.discord_alerts_home
    data:
      message: >
        The garage door sensor's body has been opened
        <@{{ states('input_text.discord_user_id') }}>
