---
- alias: Garage Door Opened
  description: Garage door has been opened
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door
    from: "off"
    to: "on"
  action:
  - delay: "00:00:45"
  - condition: state
    entity_id: person.james
    state: not_home
  - service: notify.telegram
    data:
      message: ⚠️ The garage door has been opened

- alias: Garage Door Left Opened
  description: Garage door has been left opened
  trigger:
  - platform: state
    entity_id: person.james
    from: home
    to: not_home
  condition:
  - condition: state
    entity_id: binary_sensor.garage_door
    state: "on"
  action:
  - service: notify.telegram
    data:
      message: ⚠️ The garage door has been left open

- alias: Garage Door Sensor Body Opened
  description: Garage door sensor body has been opened up
  trigger:
  - platform: state
    entity_id: sensor.garage_door_tamper_alarm
    from: "0"
    to: "3"
  action:
  - service: notify.telegram
    data:
      message: ⚠️ The garage door sensor's body has been opened
