---
- alias: Login Failure
  trigger:
  - platform: state
    entity_id: persistent_notification.http_login
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != ''None'' }}'
  action:
  - service: notify.telegram
    data:
      message: >
        🔐 A failed login attempt has occurred from
        `{{ states.persistent_notification.http_login.attributes.message.split("from")[1] | replace(' ', '') }}`

- alias: Home Assistant Update Available Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: "on"
  action:
  - service: notify.telegram
    data:
      message: 🆕 Home Assistant `{{ state_attr('binary_sensor.updater', 'newest_version') }}` is available

- alias: Home Assistant Startup
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: frontend.set_theme
    data:
      name: slate
  - service: notify.telegram
    data:
      message: 🔁 Home Assistant has been restarted

- alias: Home Assistant Shutdown
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: notify.telegram
    data:
      message: 🛑 Home Assistant is shutting down
