---
- alias: Turn Off Master Bedroom HVAC When Leaving
  description: Turn off master bedroom HVAC when leaving
  trigger:
  - platform: state
    entity_id: person.james
    from: home
    to: not_home
  condition:
  - condition: template
    value_template: "{{ not is_state('climate.master_bedroom', 'off') }}"
  action:
  - delay: "00:05:00"
  - condition: state
    entity_id: person.james
    state: not_home
  - service: climate.set_hvac_mode
    data_template:
      entity_id: climate.master_bedroom
      hvac_mode: "off"

- alias: Turn Off Master Bedroom HVAC After Bedtime
  description: Turn off master bedroom HVAC after bedtime
  trigger:
  - platform: time
    at: "01:30:00"
  condition:
  - condition: template
    value_template: "{{ not is_state('climate.master_bedroom', 'off') }}"
  action:
  - service: climate.set_hvac_mode
    data_template:
      entity_id: climate.master_bedroom
      hvac_mode: "off"

- alias: Turn Off Main HVAC When Leaving
  description: Turn off main HVAC when leaving
  trigger:
  - platform: state
    entity_id: person.james
    from: home
    to: not_home
  condition:
  - condition: template
    value_template: "{{ not is_state('climate.main_room', 'off') }}"
  action:
  - delay: "00:05:00"
  - condition: state
    entity_id: person.james
    state: not_home
  - service: climate.set_hvac_mode
    data_template:
      entity_id: climate.main_room
      hvac_mode: "off"

- alias: Turn Off Main HVAC At Night
  description: Turn off main HVAC at night bedtime
  trigger:
  - platform: time
    at: "22:30:00"
  condition:
  - condition: template
    value_template: "{{ not is_state('climate.main_room', 'off') }}"
  action:
  - service: climate.set_hvac_mode
    data_template:
      entity_id: climate.main_room
      hvac_mode: "off"
