---
- platform: discord
  name: Discord
  token: !secret discord_bot_token

- platform: group
  name: discord_alerts_home
  services:
  - service: discord
    data:
      target:
      - !secret discord_channel_id_alerts_home
- platform: group
  name: discord_alerts_system
  services:
  - service: discord
    data:
      target:
      - !secret discord_channel_id_alerts_system
- platform: group
  name: discord_alerts_system_debug
  services:
  - service: discord
    data:
      target:
      - !secret discord_channel_id_alerts_system_debug
- platform: group
  name: discord_alerts_testing
  services:
  - service: discord
    data:
      target:
      - !secret discord_channel_id_alerts_testing
